stages:
  - build

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

build-master:
  variables:
    IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $IMAGE  || true
    - docker build --cache-from $IMAGE -t $IMAGE .
    - docker push $IMAGE
